import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { NavHeader } from '../../components/Layout/NavHeader';
import { SideBarAdmin } from '../../components/Layout/Sidebars/SidebarAdmin';
import { BalanceDays, EditBalanceModal } from '../../components/Modals/EditBalanceModal';
import { StaffTable } from '../../components/StaffDirectory/StaffTable';

const StaffDirectory: NextPage = () => {
  const [editBalanceModalVisibility, setEditBalanceModalVisibility] = React.useState<boolean>(false);
  const [balanceDays, setBalanceDays] = React.useState<BalanceDays>({compDays: 0, vacationDays: 0});

  const openEditBalanceModal = (balance: BalanceDays) => {
    setBalanceDays({
      compDays: (balance?.compDays) ? balance.compDays : 0,
      vacationDays: (balance?.vacationDays) ? balance.vacationDays : 0
    });

    setEditBalanceModalVisibility(true);
  }

  const closeEditBalanceModal = () => {
    setEditBalanceModalVisibility(false);
  }

  return (
    <div className='container'>
      <Head>
        <title>Profile | Time Off App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHeader />
      <div className="body row mx-0">
        <SideBarAdmin />
        <div className="col-8">
          <div className="content">
            <StaffTable openEditBalanceModal={openEditBalanceModal} />
            <EditBalanceModal balance={balanceDays} visibility={editBalanceModalVisibility} closeModal={closeEditBalanceModal} />
          </div>
        </div>
      </div>
      
    </div>
  )
}

export default StaffDirectory
