import type { NextPage } from 'next'
import Head from 'next/head'
import { MyBalance } from '../../components/Profile/MyBalance'
import { PersonalDetails } from '../../components/Profile/PersonalDetails'
import { NavHeader } from '../../components/Layout/NavHeader'
import { SideBar } from '../../components/Layout/Sidebar'

const Profile: NextPage = () => {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHeader></NavHeader>
      <div className='body row'>
        <SideBar/>
        <div className='content col-sm-8'>
          
          <PersonalDetails/>
          <MyBalance/>
        </div>
      </div>
      
    </div>
  )
}

export default Profile
