import type { NextPage } from 'next'
import Head from 'next/head'
import { MyBalance } from '../../components/Profile/MyBalance'
import { PersonalDetails } from '../../components/Profile/PersonalDetails'
import { NavHeader } from '../../components/Layout/NavHeader'

const Profile: NextPage = () => {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHeader></NavHeader>
      <div className='container'>
        <PersonalDetails/>
        <MyBalance/>
      </div>
    </div>
  )
}

export default Profile
