import * as React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { NavHeader } from '../../components/Layout/NavHeader';
import { SideBar } from '../../components/Layout/Sidebar';
import { Request } from '../../components/TimeOffRequest/Request';
import { MyBalance } from '../../components/TimeOffRequest/MyBalance';
import { CreatedModal } from '../../components/Modals/CreatedModal';

const timeOffRequest: NextPage = () => {
  return (
    <div className='container'>
      <Head>
        <title>Time Off Request | Time Off App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHeader></NavHeader>
      <div className='body row'>
        <SideBar/>
        <Request />
        <MyBalance />
        <CreatedModal />
      </div>
      
    </div>
  )
}
export default timeOffRequest;